// ignore_for_file: non_constant_identifier_names

import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:easy_onvif/media1.dart';
import 'package:easy_onvif/onvif.dart';
import 'package:easy_onvif/probe.dart' as probe_models;

/// Extracts a required string field from a JS options object.
String _readString(JSObject options, String key, {String? fallback}) {
  final value = options.getProperty<JSAny?>(key.toJS);

  if (value == null) {
    if (fallback != null) return fallback;
    throw ArgumentError.value(null, key, 'required option is missing');
  }

  if (value.isA<JSString>()) return (value as JSString).toDart;

  return value.toString();
}

/// A small registry of live [Onvif] instances keyed by an opaque integer
/// handle that is safe to pass back to JavaScript.
final Map<int, Onvif> _handles = <int, Onvif>{};
int _nextHandle = 1;

/// Registers [onvif] and returns its integer handle.
int registerHandle(Onvif onvif) {
  final id = _nextHandle++;
  _handles[id] = onvif;
  return id;
}

Onvif _requireHandle(int id) {
  final onvif = _handles[id];

  if (onvif == null) {
    throw StateError(
      'No ONVIF connection registered for handle $id. Did you already call '
      'disconnect(), or is the handle stale?',
    );
  }

  return onvif;
}

// ── ProbeMatch → JS conversion ──────────────────────────────────────────────

JSObject _probeMatchToJs(probe_models.ProbeMatch match) {
  final json = <String, dynamic>{
    'types': match.types,
    'scopes': match.scopes,
    'xAddrs': match.xAddrs,
    'metadataVersion': match.metadataVersion,
    'endpointReference': {'address': match.endpointReference.address},
  };

  return json.jsify() as JSObject;
}

// ── Generic JSON serialization helpers ───────────────────────────────────────

Map<String, dynamic> _sanitize(Map<String, dynamic> json) {
  final result = <String, dynamic>{};
  for (final entry in json.entries) {
    final key = entry.key;
    if (key.contains(':')) continue;
    if (key.startsWith('@xmlns') || key.startsWith('@xsi')) continue;
    if (key.startsWith('@')) {
      // Promote attributes like '@token' to 'token' so JS callers can read
      // `profile.token` without worrying about the XML attribute marker.
      final bare = key.substring(1);
      result.putIfAbsent(bare, () => _deepJsonify(entry.value));
      continue;
    }
    result[key] = _deepJsonify(entry.value);
  }
  return result;
}

/// Recursively converts an arbitrary Dart value into a JSON-compatible
/// tree of `Map<String, dynamic>`, `List<dynamic>`, and primitives.
///
/// This is required before calling `jsify()` because `jsify` does NOT recurse
/// into opaque Dart objects; any non-Map / non-List / non-primitive value is
/// passed through as an opaque JS proxy whose properties carry dart2js's
/// minified field names. We avoid that by walking the graph and invoking
/// each object's own `toJson()` (generated by `json_serializable`).
Object? _deepJsonify(Object? value) {
  if (value == null) return null;
  if (value is String || value is num || value is bool) return value;
  if (value is Map) {
    return _sanitize(
      Map<String, dynamic>.from(value.map((k, v) => MapEntry(k.toString(), v))),
    );
  }
  if (value is List) {
    return <dynamic>[for (final item in value) _deepJsonify(item)];
  }
  try {
    final json = (value as dynamic).toJson();
    if (json is Map<String, dynamic>) return _sanitize(json);
    if (json is Map) {
      return _sanitize(
        Map<String, dynamic>.from(
          json.map((k, v) => MapEntry(k.toString(), v)),
        ),
      );
    }
    return _deepJsonify(json);
  } catch (_) {
    return value.toString();
  }
}

JSObject _toJsonJs(Object? obj) {
  if (obj == null) return <String, dynamic>{}.jsify() as JSObject;

  // Primitives: wrap under `value` so the return shape is always an object.
  if (obj is String) {
    return <String, dynamic>{'value': obj}.jsify() as JSObject;
  }
  if (obj is num || obj is bool) {
    return <String, dynamic>{'value': obj}.jsify() as JSObject;
  }

  final jsonified = _deepJsonify(obj);
  if (jsonified is Map) {
    return (jsonified as Map<String, dynamic>).jsify() as JSObject;
  }
  return <String, dynamic>{'value': jsonified}.jsify() as JSObject;
}

JSArray<JSObject> _toListJs<T>(List<T> items) {
  return <JSObject>[for (final item in items) _toJsonJs(item)].toJS;
}

// ── Main API class ──────────────────────────────────────────────────────────

@JSExport()
class OnvifApiCore {
  JSPromise<JSNumber> connect(JSObject options) {
    return (() async {
      final onvif = await Onvif.connect(
        host: _readString(options, 'host'),
        username: _readString(options, 'username'),
        password: _readString(options, 'password'),
      );

      return registerHandle(onvif).toJS;
    })().toJS;
  }

  void disconnect(int handle) {
    _handles.remove(handle);
  }

  // ── Service object factories ─────────────────────────────────────────────
  //
  // These do NOT validate the handle upfront; each individual service method
  // calls `_requireHandle(handle)` on invocation, so an invalid handle will
  // surface as an async rejection at the point of use rather than eagerly at
  // service-object construction. This allows callers to cache service objects.

  JSObject getDeviceManagement(int handle) =>
      _createDeviceManagementService(handle);

  JSObject getMedia(int handle) => _createMediaService(handle);

  JSObject getPtz(int handle) => _createPtzService(handle);

  JSObject getImaging(int handle) => _createImagingService(handle);

  JSObject getSearch(int handle) => _createSearchService(handle);

  JSObject getRecordings(int handle) => _createRecordingsService(handle);

  JSObject getReplay(int handle) => _createReplayService(handle);

  JSObject convertProbeMatch(probe_models.ProbeMatch match) =>
      _probeMatchToJs(match);
}

// ── Service object creation helpers ─────────────────────────────────────────

/// Service creation helpers use inline `.toJS` conversion on typed closure
/// literals so dart2js has the precise function type it needs.

JSObject _createDeviceManagementService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getDeviceInformation'.toJS,
    (() => _deviceMgmtGetDeviceInformation(handle)).toJS,
  );
  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _deviceMgmtGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getServices'.toJS,
    (([JSAny? includeCapability]) {
      final include =
          includeCapability != null && includeCapability.isA<JSBoolean>()
          ? (includeCapability as JSBoolean).toDart
          : false;
      return _deviceMgmtGetServices(handle, include);
    }).toJS,
  );
  obj.setProperty(
    'getCapabilities'.toJS,
    (() => _deviceMgmtGetCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getHostname'.toJS,
    (() => _deviceMgmtGetHostname(handle)).toJS,
  );
  obj.setProperty('getDNS'.toJS, (() => _deviceMgmtGetDNS(handle)).toJS);
  obj.setProperty('getNTP'.toJS, (() => _deviceMgmtGetNTP(handle)).toJS);
  obj.setProperty(
    'getSystemDateAndTime'.toJS,
    (() => _deviceMgmtGetSystemDateAndTime(handle)).toJS,
  );
  obj.setProperty('getUsers'.toJS, (() => _deviceMgmtGetUsers(handle)).toJS);
  obj.setProperty(
    'systemReboot'.toJS,
    (() => _deviceMgmtSystemReboot(handle)).toJS,
  );
  obj.setProperty(
    'getDiscoveryMode'.toJS,
    (() => _deviceMgmtGetDiscoveryMode(handle)).toJS,
  );

  return obj;
}

JSObject _createMediaService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _mediaGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty('getProfiles'.toJS, (() => _mediaGetProfiles(handle)).toJS);
  obj.setProperty(
    'getProfile'.toJS,
    ((JSString token) => _mediaGetProfile(handle, token.toDart)).toJS,
  );
  obj.setProperty(
    'getStreamUri'.toJS,
    ((JSString profileToken, [JSAny? streamSetup]) {
      final setup = (streamSetup != null && streamSetup.isA<JSObject>())
          ? streamSetup as JSObject
          : null;
      return _mediaGetStreamUri(handle, profileToken.toDart, setup);
    }).toJS,
  );
  obj.setProperty(
    'getSnapshotUri'.toJS,
    ((JSString profileToken) => _mediaGetSnapshotUri(
      handle,
      profileToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getMetadataConfiguration'.toJS,
    ((JSString token) => _mediaGetMetadataConfiguration(
      handle,
      token.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getMetadataConfigurations'.toJS,
    (() => _mediaGetMetadataConfigurations(handle)).toJS,
  );
  obj.setProperty(
    'getSnapshotUri2'.toJS,
    ((JSString profileToken) => _mediaGetSnapshotUri2(
      handle,
      profileToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getStreamUri2'.toJS,
    ((JSString profileToken, [JSAny? streamSetup]) {
      final setup = (streamSetup != null && streamSetup.isA<JSObject>())
          ? streamSetup as JSObject
          : null;
      return _mediaGetStreamUri2(handle, profileToken.toDart, setup);
    }).toJS,
  );

  return obj;
}

JSObject _createPtzService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _ptzGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getConfigurations'.toJS,
    (() => _ptzGetConfigurations(handle)).toJS,
  );
  obj.setProperty(
    'getConfiguration'.toJS,
    ((JSString token) => _ptzGetConfiguration(handle, token.toDart)).toJS,
  );
  obj.setProperty(
    'getConfigurationOptions'.toJS,
    ((JSString token) => _ptzGetConfigurationOptions(
      handle,
      token.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getPresets'.toJS,
    ((JSString profileToken) => _ptzGetPresets(
      handle,
      profileToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getStatus'.toJS,
    ((JSString profileToken) => _ptzGetStatus(
      handle,
      profileToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'stop'.toJS,
    ((JSString profileToken) => _ptzStop(handle, profileToken.toDart)).toJS,
  );
  obj.setProperty(
    'setHomePosition'.toJS,
    ((JSString profileToken) => _ptzSetHomePosition(
      handle,
      profileToken.toDart,
    )).toJS,
  );

  return obj;
}

JSObject _createImagingService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _imagingGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getImagingSettings'.toJS,
    ((JSString videoSourceToken) => _imagingGetImagingSettings(
      handle,
      videoSourceToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'setImagingSettings'.toJS,
    ((JSObject options) => _imagingSetImagingSettings(handle, options)).toJS,
  );
  obj.setProperty(
    'getOptions'.toJS,
    ((JSString videoSourceToken) => _imagingGetOptions(
      handle,
      videoSourceToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'move'.toJS,
    ((JSObject options) => _imagingMove(handle, options)).toJS,
  );
  obj.setProperty(
    'getStatus'.toJS,
    ((JSString videoSourceToken) => _imagingGetStatus(
      handle,
      videoSourceToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'stop'.toJS,
    ((JSString videoSourceToken) => _imagingStop(
      handle,
      videoSourceToken.toDart,
    )).toJS,
  );

  return obj;
}

JSObject _createSearchService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getSearchCapabilities'.toJS,
    (() => _searchGetSearchCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getRecordingSummary'.toJS,
    (() => _searchGetRecordingSummary(handle)).toJS,
  );
  obj.setProperty(
    'findRecordings'.toJS,
    (([JSAny? keepAliveTime]) {
      final keep = (keepAliveTime != null && keepAliveTime.isA<JSNumber>())
          ? (keepAliveTime as JSNumber).toDartInt
          : 300;
      return _searchFindRecordings(handle, keep);
    }).toJS,
  );
  obj.setProperty(
    'findEvents'.toJS,
    ((JSObject options) => _searchFindEvents(handle, options)).toJS,
  );

  return obj;
}

JSObject _createRecordingsService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _recordingsGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getRecordings'.toJS,
    (() => _recordingsGetRecordings(handle)).toJS,
  );
  obj.setProperty(
    'getRecordingConfiguration'.toJS,
    ((JSString recordingToken) => _recordingsGetRecordingConfiguration(
      handle,
      recordingToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'setRecordingConfiguration'.toJS,
    ((JSObject options) => _recordingsSetRecordingConfiguration(
      handle,
      options,
    )).toJS,
  );
  obj.setProperty(
    'createRecording'.toJS,
    ((JSObject recordingConfiguration) => _recordingsCreateRecording(
      handle,
      recordingConfiguration,
    )).toJS,
  );
  obj.setProperty(
    'deleteRecording'.toJS,
    ((JSString recordingToken) => _recordingsDeleteRecording(
      handle,
      recordingToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'getRecordingJobs'.toJS,
    (() => _recordingsGetRecordingJobs(handle)).toJS,
  );
  obj.setProperty(
    'getRecordingJobConfiguration'.toJS,
    ((JSString jobToken) => _recordingsGetRecordingJobConfiguration(
      handle,
      jobToken.toDart,
    )).toJS,
  );
  obj.setProperty(
    'setRecordingJobConfiguration'.toJS,
    ((JSObject options) => _recordingsSetRecordingJobConfiguration(
      handle,
      options,
    )).toJS,
  );
  obj.setProperty(
    'createRecordingJob'.toJS,
    ((JSObject jobConfiguration) => _recordingsCreateRecordingJob(
      handle,
      jobConfiguration,
    )).toJS,
  );
  obj.setProperty(
    'deleteRecordingJob'.toJS,
    ((JSString jobToken) => _recordingsDeleteRecordingJob(
      handle,
      jobToken.toDart,
    )).toJS,
  );

  return obj;
}

JSObject _createReplayService(int handle) {
  final obj = JSObject();

  obj.setProperty(
    'getServiceCapabilities'.toJS,
    (() => _replayGetServiceCapabilities(handle)).toJS,
  );
  obj.setProperty(
    'getReplayUri'.toJS,
    ((JSString recordingToken, [JSAny? streamSetup]) {
      final setup = (streamSetup != null && streamSetup.isA<JSObject>())
          ? streamSetup as JSObject
          : null;
      return _replayGetReplayUri(handle, recordingToken.toDart, setup);
    }).toJS,
  );
  obj.setProperty(
    'getReplayConfiguration'.toJS,
    (() => _replayGetReplayConfiguration(handle)).toJS,
  );
  obj.setProperty(
    'setReplayConfiguration'.toJS,
    ((JSObject config) => _replaySetReplayConfiguration(handle, config)).toJS,
  );

  return obj;
}

// ── Device Management service methods ───────────────────────────────────────

JSPromise<JSObject> _deviceMgmtGetDeviceInformation(int handle) {
  return (() async {
    final info = await _requireHandle(
      handle,
    ).deviceManagement.getDeviceInformation();
    return <String, dynamic>{
          'manufacturer': info.manufacturer,
          'model': info.model,
          'firmwareVersion': info.firmwareVersion,
          'serialNumber': info.serialNumber,
          'hardwareId': info.hardwareId,
        }.jsify()
        as JSObject;
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(
      handle,
    ).deviceManagement.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _deviceMgmtGetServices(
  int handle,
  bool includeCapability,
) {
  return (() async {
    final services = await _requireHandle(
      handle,
    ).deviceManagement.getServices(includeCapability: includeCapability);
    return _toListJs(services);
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(
      handle,
    ).deviceManagement.getCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetHostname(int handle) {
  return (() async {
    final hostname = await _requireHandle(
      handle,
    ).deviceManagement.getHostname();
    return _toJsonJs(hostname);
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetDNS(int handle) {
  return (() async {
    final dns = await _requireHandle(handle).deviceManagement.getDns();
    return _toJsonJs(dns);
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetNTP(int handle) {
  return (() async {
    final ntp = await _requireHandle(handle).deviceManagement.getNtp();
    return _toJsonJs(ntp);
  })().toJS;
}

JSPromise<JSObject> _deviceMgmtGetSystemDateAndTime(int handle) {
  return (() async {
    final dt = await _requireHandle(
      handle,
    ).deviceManagement.getSystemDateAndTime();
    return <String, dynamic>{
          'dateTimeType': dt.dateTimeType,
          'daylightSavings': dt.daylightSavings,
          'timeZone': dt.timeZone?.toJson(),
          'utcDateTime': dt.utcDateTime?.toIso8601String(),
          'localDateTime': dt.localDateTime?.toIso8601String(),
        }.jsify()
        as JSObject;
  })().toJS;
}

JSPromise<JSArray<JSObject>> _deviceMgmtGetUsers(int handle) {
  return (() async {
    final users = await _requireHandle(handle).deviceManagement.getUsers();
    return _toListJs(users);
  })().toJS;
}

JSPromise _deviceMgmtSystemReboot(int handle) {
  return (() async {
    await _requireHandle(handle).deviceManagement.systemReboot();
  })().toJS;
}

JSPromise<JSString> _deviceMgmtGetDiscoveryMode(int handle) {
  return (() async {
    final mode = await _requireHandle(
      handle,
    ).deviceManagement.getDiscoveryMode();
    return mode.toJS;
  })().toJS;
}

// ── Media service methods ───────────────────────────────────────────────────

JSPromise<JSObject> _mediaGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(handle).media.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _mediaGetProfiles(int handle) {
  return (() async {
    final profiles = await _requireHandle(handle).media.getProfiles();
    return _toListJs(profiles);
  })().toJS;
}

JSPromise<JSObject> _mediaGetProfile(int handle, String token) {
  return (() async {
    final profile = await _requireHandle(handle).media.getProfile(token);
    return _toJsonJs(profile);
  })().toJS;
}

JSPromise<JSObject> _mediaGetStreamUri(
  int handle,
  String profileToken, [
  JSObject? streamSetup,
]) {
  return (() async {
    final uri = await _requireHandle(handle).media.getStreamUri(profileToken);
    return _toJsonJs(uri);
  })().toJS;
}

JSPromise<JSObject> _mediaGetSnapshotUri(int handle, String profileToken) {
  return (() async {
    final uri = await _requireHandle(handle).media.getSnapshotUri(profileToken);
    return _toJsonJs(uri);
  })().toJS;
}

JSPromise<JSObject> _mediaGetMetadataConfiguration(int handle, String token) {
  return (() async {
    final config = await _requireHandle(
      handle,
    ).media.getMetadataConfiguration(token);
    return _toJsonJs(config);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _mediaGetMetadataConfigurations(int handle) {
  return (() async {
    final configs = await _requireHandle(
      handle,
    ).media.getMetadataConfigurations();
    return _toListJs(configs);
  })().toJS;
}

JSPromise<JSObject> _mediaGetSnapshotUri2(int handle, String profileToken) {
  return (() async {
    final uri = await _requireHandle(
      handle,
    ).media.getSnapshotUri2(profileToken);
    return _toJsonJs(uri);
  })().toJS;
}

JSPromise<JSObject> _mediaGetStreamUri2(
  int handle,
  String profileToken, [
  JSObject? streamSetup,
]) {
  return (() async {
    final uri = await _requireHandle(handle).media.getStreamUri2(profileToken);
    return _toJsonJs(uri);
  })().toJS;
}

// ── PTZ service methods ─────────────────────────────────────────────────────

JSPromise<JSObject> _ptzGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(handle).ptz.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _ptzGetConfigurations(int handle) {
  return (() async {
    final configs = await _requireHandle(handle).ptz.getConfigurations();
    return _toListJs(configs);
  })().toJS;
}

JSPromise<JSObject> _ptzGetConfiguration(int handle, String token) {
  return (() async {
    final config = await _requireHandle(handle).ptz.getConfiguration(token);
    return _toJsonJs(config);
  })().toJS;
}

JSPromise<JSObject> _ptzGetConfigurationOptions(int handle, String token) {
  return (() async {
    final opts = await _requireHandle(
      handle,
    ).ptz.getConfigurationOptions(token);
    return _toJsonJs(opts);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _ptzGetPresets(int handle, String profileToken) {
  return (() async {
    final presets = await _requireHandle(handle).ptz.getPresets(profileToken);
    return _toListJs(presets);
  })().toJS;
}

JSPromise<JSObject> _ptzGetStatus(int handle, String profileToken) {
  return (() async {
    final status = await _requireHandle(handle).ptz.getStatus(profileToken);
    return _toJsonJs(status);
  })().toJS;
}

JSPromise _ptzStop(int handle, String profileToken) {
  return (() async {
    await _requireHandle(handle).ptz.stop(profileToken);
  })().toJS;
}

JSPromise _ptzSetHomePosition(int handle, String profileToken) {
  return (() async {
    await _requireHandle(handle).ptz.setHomePosition(profileToken);
  })().toJS;
}

// ── Imaging service methods ─────────────────────────────────────────────────

JSPromise<JSObject> _imagingGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(handle).imaging.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSObject> _imagingGetImagingSettings(
  int handle,
  String videoSourceToken,
) {
  return (() async {
    // Note: Not available on Imaging class
    throw UnimplementedError('getImagingSettings not available');
  })().toJS;
}

JSPromise _imagingSetImagingSettings(int handle, JSObject options) {
  return (() async {
    // Note: Parse options and call setImagingSettings
  })().toJS;
}

JSPromise<JSObject> _imagingGetOptions(int handle, String videoSourceToken) {
  return (() async {
    // Note: Not available on Imaging class
    throw UnimplementedError('getOptions not available');
  })().toJS;
}

JSPromise _imagingMove(int handle, JSObject options) {
  return (() async {
    // Note: Parse options and call move
  })().toJS;
}

JSPromise<JSObject> _imagingGetStatus(int handle, String videoSourceToken) {
  return (() async {
    final status = await _requireHandle(
      handle,
    ).imaging.getStatus(videoSourceToken);
    return _toJsonJs(status);
  })().toJS;
}

JSPromise _imagingStop(int handle, String videoSourceToken) {
  return (() async {
    // Note: Not available on Imaging class
    throw UnimplementedError('stop not available');
  })().toJS;
}

// ── Search service methods ──────────────────────────────────────────────────

JSPromise<JSObject> _searchGetSearchCapabilities(int handle) {
  return (() async {
    // Note: Not available on Search class
    throw UnimplementedError('getSearchCapabilities not available');
  })().toJS;
}

JSPromise<JSObject> _searchGetRecordingSummary(int handle) {
  return (() async {
    final summary = await _requireHandle(handle).search.getRecordingSummary();
    return _toJsonJs(summary);
  })().toJS;
}

JSPromise<JSString> _searchFindRecordings(int handle, int keepAliveTime) {
  return (() async {
    final searchToken = await _requireHandle(
      handle,
    ).search.findRecordings(keepAliveTime: keepAliveTime);
    return searchToken.toJS;
  })().toJS;
}

JSPromise<JSObject> _searchFindEvents(int handle, JSObject options) {
  return (() async {
    // Note: Parse options and call findEvents
    return <String, dynamic>{}.jsify() as JSObject;
  })().toJS;
}

// ── Recordings service methods ──────────────────────────────────────────────

JSPromise<JSObject> _recordingsGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(
      handle,
    ).recordings.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _recordingsGetRecordings(int handle) {
  return (() async {
    final recordings = await _requireHandle(handle).recordings.getRecordings();
    return _toListJs(recordings);
  })().toJS;
}

JSPromise<JSObject> _recordingsGetRecordingConfiguration(
  int handle,
  String recordingToken,
) {
  return (() async {
    // Note: Not available on Recordings class
    throw UnimplementedError('getRecordingConfiguration not available');
  })().toJS;
}

JSPromise _recordingsSetRecordingConfiguration(int handle, JSObject options) {
  return (() async {
    // Note: Parse options and call setRecordingConfiguration
  })().toJS;
}

JSPromise<JSString> _recordingsCreateRecording(
  int handle,
  JSObject recordingConfiguration,
) {
  return (() async {
    // Note: Parse recordingConfiguration and call createRecording
    return ''.toJS;
  })().toJS;
}

JSPromise _recordingsDeleteRecording(int handle, String recordingToken) {
  return (() async {
    await _requireHandle(handle).recordings.deleteRecording(recordingToken);
  })().toJS;
}

JSPromise<JSArray<JSObject>> _recordingsGetRecordingJobs(int handle) {
  return (() async {
    final jobs = await _requireHandle(handle).recordings.getRecordingJobs();
    return _toListJs(jobs);
  })().toJS;
}

JSPromise<JSObject> _recordingsGetRecordingJobConfiguration(
  int handle,
  String jobToken,
) {
  return (() async {
    // Note: Not available on Recordings class
    throw UnimplementedError('getRecordingJobConfiguration not available');
  })().toJS;
}

JSPromise _recordingsSetRecordingJobConfiguration(
  int handle,
  JSObject options,
) {
  return (() async {
    // Note: Parse options and call setRecordingJobConfiguration
  })().toJS;
}

JSPromise<JSString> _recordingsCreateRecordingJob(
  int handle,
  JSObject jobConfiguration,
) {
  return (() async {
    // Note: Parse jobConfiguration and call createRecordingJob
    return ''.toJS;
  })().toJS;
}

JSPromise _recordingsDeleteRecordingJob(int handle, String jobToken) {
  return (() async {
    await _requireHandle(handle).recordings.deleteRecordingJob(jobToken);
  })().toJS;
}

// ── Replay service methods ──────────────────────────────────────────────────

JSPromise<JSObject> _replayGetServiceCapabilities(int handle) {
  return (() async {
    final caps = await _requireHandle(handle).replay.getServiceCapabilities();
    return _toJsonJs(caps);
  })().toJS;
}

JSPromise<JSObject> _replayGetReplayUri(
  int handle,
  String recordingToken, [
  JSObject? streamSetup,
]) {
  return (() async {
    final uri = await _requireHandle(handle).replay.getReplayUri(
      recordingToken,
      streamSetup: StreamSetup(
        stream: 'RTP-Unicast',
        transport: Transport(protocol: 'RTSP'),
      ),
    );
    return _toJsonJs(uri);
  })().toJS;
}

JSPromise<JSObject> _replayGetReplayConfiguration(int handle) {
  return (() async {
    final config = await _requireHandle(handle).replay.getReplayConfiguration();
    return _toJsonJs(config);
  })().toJS;
}

JSPromise _replaySetReplayConfiguration(int handle, JSObject config) {
  return (() async {
    // Note: Parse config and call setReplayConfiguration
  })().toJS;
}
