name: easy_onvif_cli
version: 3.1.5
homepage: https://github.com/cdavis-code/easy_onvif_workspace/tree/main/packages/easy_onvif_cli
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices.
repository: https://github.com/cdavis-code/easy_onvif_workspace/tree/main/packages/easy_onvif_cli
issue_tracker: https://github.com/cdavis-code/easy_onvif_workspace/issues

funding:
  - https://www.buymeacoffee.com/cdavis

topics:
  - onvif
  - camera
  - cli
  - automation
  - iot

environment:
  sdk: ">=3.10.0 <4.0.0"

executables:
  onvif:

resolution: workspace

dependencies:
  archive: ^4.0.9
  args: ^2.7.0
  ansicolor: ^2.0.3
  ansi_escapes: ^2.0.1
  cli_spin: ^1.0.1
  easy_onvif: ^3.1.5
  # easy_onvif:
  #   path: ../easy_onvif
  dio: ^5.10.0
  loggy: ^2.0.3
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.6.0
  yaml: ^3.1.3

